title: "log_puck"
description: "Esplorazioni creative sull'intelligenza artificiale."

url: "https://log-puck.github.io"
baseurl: "/log-puck-blog"

markdown: kramdown
permalink: /:categories/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - README.md
  - .github